// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Afiliados
{
    public int AfiliadoId { get; set; }

    public int PlanObraSocialId { get; set; }

    public int ClienteId { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<Coberturas> Coberturas { get; set; } = new List<Coberturas>();

    public virtual PlanesObrasSociales PlanObraSocial { get; set; }

    public virtual ICollection<Recetas> Recetas { get; set; } = new List<Recetas>();
}