// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Clientes
{
    public int ClienteId { get; set; }

    public string NombreCliente { get; set; }

    public string ApellidoCliente { get; set; }

    public DateOnly? FechaNacimientoCliente { get; set; }

    public string TelefonoCliente { get; set; }

    public int? TipoDocumentoId { get; set; }

    public string DireccionCliente { get; set; }

    public int? LocalidadId { get; set; }

    public string EmailCliente { get; set; }

    public string DocumentoCliente { get; set; }

    public virtual ICollection<Afiliados> Afiliados { get; set; } = new List<Afiliados>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Localidades Localidad { get; set; }

    public virtual TiposDocumentos TipoDocumento { get; set; }
}