// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class Compras
{
    public int CompraId { get; set; }

    public DateTime? FechaCompra { get; set; }

    public int? EmpleadoId { get; set; }

    public int? ProveedorId { get; set; }

    public int? RepartidorId { get; set; }

    public int? SucursalId { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<DetallesCompras> DetallesCompras { get; set; } = new List<DetallesCompras>();
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
    [JsonIgnore]
    public virtual Proveedores Proveedor { get; set; }
    [JsonIgnore]
    public virtual Repartidores Repartidor { get; set; }
    [JsonIgnore]
    public virtual Sucursales Sucursal { get; set; }
}