// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class DetallesFacturas
{
    public int NroDetalleId { get; set; }

    public int? DescuentoId { get; set; }

    public int? ProductoId { get; set; }

    public int? MedicamentoId { get; set; }

    public int Cantidad { get; set; }

    public decimal? Precio { get; set; }

    public int? CoberturaId { get; set; }

    public int? FacturaId { get; set; }

    public virtual Coberturas Cobertura { get; set; }

    public virtual Descuentos Descuento { get; set; }

    public virtual Facturas Factura { get; set; }

    public virtual Medicamentos Medicamento { get; set; }

    public virtual Productos Producto { get; set; }
}