// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class DetallesCompras
{
    public int DetalleCompraId { get; set; }

    public int CompraId { get; set; }

    public int? LoteProductoId { get; set; }

    public string CodigoBarraMedicamentoId { get; set; }

    public string CodigoBarraProductoId { get; set; }

    public int Cantidad { get; set; }

    public int? LoteMedicamentoId { get; set; }

    public bool? Activo { get; set; }
    [JsonIgnore]
    public virtual Compras Compra { get; set; }
    [JsonIgnore]
    public virtual LotesMedicamentos LoteMedicamento { get; set; }
    [JsonIgnore]
    public virtual LotesProductos LoteProducto { get; set; }
}