// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class DetallesRecetas
{
    public int DetalleRecetaId { get; set; }

    public int RecetaId { get; set; }

    public int Cantidad { get; set; }

    public int? MedicamentoId { get; set; }

    public virtual Medicamentos Medicamento { get; set; }

    public virtual Recetas Receta { get; set; }
}