// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Doctores
{
    public int DoctorId { get; set; }

    public string NombreDoctor { get; set; }

    public string ApellidoDoctor { get; set; }

    public string MatriculaDoctor { get; set; }

    public int? EspecialidadId { get; set; }

    public virtual EspecialidadesMedicos Especialidad { get; set; }

    public virtual ICollection<Recetas> Recetas { get; set; } = new List<Recetas>();
}