// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Empleados
{
    public int EmpleadoId { get; set; }

    public string NombreEmpleado { get; set; }

    public string ApellidoEmpleado { get; set; }

    public DateOnly? FechaNacimientoEmpleado { get; set; }

    public string DireccionEmpleado { get; set; }

    public string TelefonoEmpleado { get; set; }

    public string EmailEmpleado { get; set; }

    public int? LocalidadId { get; set; }

    public int? TipoDocumentoId { get; set; }

    public string DocumentoEmpleado { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();

    public virtual ICollection<EmpleadosSucursales> EmpleadosSucursales { get; set; } = new List<EmpleadosSucursales>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Localidades Localidad { get; set; }

    public virtual TiposDocumentos TipoDocumento { get; set; }
}