// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class EmpleadosSucursales
{
    public int EmpleadoSucursalId { get; set; }

    public int EmpleadoId { get; set; }

    public int SucursalId { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public virtual Empleados Empleado { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}