// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class EspecialidadesMedicos
{
    public int EspecialidadId { get; set; }

    public string NombreEspecialidad { get; set; }

    public virtual ICollection<Doctores> Doctores { get; set; } = new List<Doctores>();
}