// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class EstadosCoberturas
{
    public int EstadoCoberturaId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Coberturas> Coberturas { get; set; } = new List<Coberturas>();
}