// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Facturas
{
    public int FacturaId { get; set; }

    public DateTime? FechaFacturacion { get; set; }

    public int? EmpleadoId { get; set; }

    public int? ClienteId { get; set; }

    public int? SucursalId { get; set; }

    public int? MetodoPagoId { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual Empleados Empleado { get; set; }

    public virtual MetodosPagos MetodoPago { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}