// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class FarmaceuticaContext : DbContext
{
    public FarmaceuticaContext(DbContextOptions<FarmaceuticaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Afiliados> Afiliados { get; set; }

    public virtual DbSet<ClasificacionesSuministros> ClasificacionesSuministros { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Coberturas> Coberturas { get; set; }

    public virtual DbSet<Compras> Compras { get; set; }

    public virtual DbSet<Descuentos> Descuentos { get; set; }

    public virtual DbSet<DetallesCompras> DetallesCompras { get; set; }

    public virtual DbSet<DetallesFacturas> DetallesFacturas { get; set; }

    public virtual DbSet<DetallesRecetas> DetallesRecetas { get; set; }

    public virtual DbSet<Doctores> Doctores { get; set; }

    public virtual DbSet<Empleados> Empleados { get; set; }

    public virtual DbSet<EmpleadosSucursales> EmpleadosSucursales { get; set; }

    public virtual DbSet<EspecialidadesMedicos> EspecialidadesMedicos { get; set; }

    public virtual DbSet<EstadosCoberturas> EstadosCoberturas { get; set; }

    public virtual DbSet<Facturas> Facturas { get; set; }

    public virtual DbSet<InventariosMedicamentos> InventariosMedicamentos { get; set; }

    public virtual DbSet<InventariosProductos> InventariosProductos { get; set; }

    public virtual DbSet<Localidades> Localidades { get; set; }

    public virtual DbSet<LotesMedicamentos> LotesMedicamentos { get; set; }

    public virtual DbSet<LotesProductos> LotesProductos { get; set; }

    public virtual DbSet<Medicamentos> Medicamentos { get; set; }

    public virtual DbSet<MetodosPagos> MetodosPagos { get; set; }

    public virtual DbSet<ObrasSociales> ObrasSociales { get; set; }

    public virtual DbSet<Paises> Paises { get; set; }

    public virtual DbSet<PlanesObrasSociales> PlanesObrasSociales { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Proveedores> Proveedores { get; set; }

    public virtual DbSet<Provincias> Provincias { get; set; }

    public virtual DbSet<Recetas> Recetas { get; set; }

    public virtual DbSet<Repartidores> Repartidores { get; set; }

    public virtual DbSet<Restricciones> Restricciones { get; set; }

    public virtual DbSet<Sucursales> Sucursales { get; set; }

    public virtual DbSet<TiposDescuentos> TiposDescuentos { get; set; }

    public virtual DbSet<TiposDocumentos> TiposDocumentos { get; set; }

    public virtual DbSet<TiposPresentaciones> TiposPresentaciones { get; set; }

    public virtual DbSet<TiposSuministros> TiposSuministros { get; set; }

    public virtual DbSet<UnidadesMedidas> UnidadesMedidas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Afiliados>(entity =>
        {
            entity.HasKey(e => e.AfiliadoId);

            entity.ToTable("AFILIADOS");

            entity.Property(e => e.AfiliadoId).HasColumnName("AfiliadoID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.PlanObraSocialId).HasColumnName("Plan_Obra_SocialID");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Afiliados)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AFILIADOS_CLIENTES");

            entity.HasOne(d => d.PlanObraSocial).WithMany(p => p.Afiliados)
                .HasForeignKey(d => d.PlanObraSocialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AFILIADOS_PLAN_OBRA");
        });

        modelBuilder.Entity<ClasificacionesSuministros>(entity =>
        {
            entity.HasKey(e => e.ClasificacionSuministroId);

            entity.ToTable("CLASIFICACIONES_SUMINISTROS");

            entity.Property(e => e.ClasificacionSuministroId).HasColumnName("Clasificacion_SuministroID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.ClienteId);

            entity.ToTable("CLIENTES");

            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.ApellidoCliente)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DireccionCliente)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DocumentoCliente)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmailCliente)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FechaNacimientoCliente).HasColumnName("Fecha_Nacimiento_Cliente");
            entity.Property(e => e.LocalidadId).HasColumnName("LocalidadID");
            entity.Property(e => e.NombreCliente)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoCliente)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TipoDocumentoId).HasColumnName("Tipo_DocumentoID");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.LocalidadId)
                .HasConstraintName("FK_CLIENTES_LOCALIDADES");

            entity.HasOne(d => d.TipoDocumento).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.TipoDocumentoId)
                .HasConstraintName("FK_CLIENTES_TIPOS_DOCUMENTOS");
        });

        modelBuilder.Entity<Coberturas>(entity =>
        {
            entity.HasKey(e => e.CoberturaId);

            entity.ToTable("COBERTURAS");

            entity.Property(e => e.CoberturaId).HasColumnName("CoberturaID");
            entity.Property(e => e.AfiliadoId).HasColumnName("AfiliadoID");
            entity.Property(e => e.EstadoCoberturaId).HasColumnName("Estado_CoberturaID");
            entity.Property(e => e.RecetaId).HasColumnName("RecetaID");
            entity.Property(e => e.ValidacionObraSocial).HasColumnName("Validacion_Obra_Social");

            entity.HasOne(d => d.Afiliado).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.AfiliadoId)
                .HasConstraintName("FK_COBERTURAS_AFILIADOS");

            entity.HasOne(d => d.EstadoCobertura).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.EstadoCoberturaId)
                .HasConstraintName("FK_COBERTURAS_ESTADOS");

            entity.HasOne(d => d.Receta).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.RecetaId)
                .HasConstraintName("FK_COBERTURAS_RECETAS");
        });

        modelBuilder.Entity<Compras>(entity =>
        {
            entity.HasKey(e => e.CompraId);

            entity.ToTable("COMPRAS");

            entity.Property(e => e.CompraId).HasColumnName("CompraID");
            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.FechaCompra)
                .HasPrecision(3)
                .HasColumnName("Fecha_Compra");
            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");
            entity.Property(e => e.RepartidorId).HasColumnName("RepartidorID");
            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Compras)
                .HasForeignKey(d => d.EmpleadoId)
                .HasConstraintName("FK_COMPRAS_EMPLEADOS");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.Compras)
                .HasForeignKey(d => d.ProveedorId)
                .HasConstraintName("FK_COMPRAS_PROVEEDORES");

            entity.HasOne(d => d.Repartidor).WithMany(p => p.Compras)
                .HasForeignKey(d => d.RepartidorId)
                .HasConstraintName("FK_COMPRAS_REPARTIDORES");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.Compras)
                .HasForeignKey(d => d.SucursalId)
                .HasConstraintName("FK_COMPRAS_SUCURSALES");
        });

        modelBuilder.Entity<Descuentos>(entity =>
        {
            entity.HasKey(e => e.DescuentoId);

            entity.ToTable("DESCUENTOS");

            entity.Property(e => e.DescuentoId).HasColumnName("DescuentoID");
            entity.Property(e => e.FechaDescuento)
                .HasPrecision(3)
                .HasColumnName("Fecha_Descuento");
            entity.Property(e => e.LocalidadId).HasColumnName("LocalidadID");
            entity.Property(e => e.ObraSocialId).HasColumnName("Obra_SocialID");
            entity.Property(e => e.PorcentajeDescuento)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("Porcentaje_Descuento");
            entity.Property(e => e.TipoDescuentoId).HasColumnName("Tipo_DescuentoID");
            entity.Property(e => e.TipoSuministroId).HasColumnName("Tipo_SuministroID");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.LocalidadId)
                .HasConstraintName("FK_DESCUENTOS_LOCALIDADES");

            entity.HasOne(d => d.ObraSocial).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.ObraSocialId)
                .HasConstraintName("FK_DESCUENTOS_OBRAS_SOCIALES");

            entity.HasOne(d => d.TipoDescuento).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.TipoDescuentoId)
                .HasConstraintName("FK_DESCUENTOS_TIPOSDESCUENTO");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.TipoSuministroId)
                .HasConstraintName("FK_DESCUENTOS_TIPOSUMINISTRO");
        });

        modelBuilder.Entity<DetallesCompras>(entity =>
        {
            entity.HasKey(e => e.DetalleCompraId);

            entity.ToTable("DETALLES_COMPRAS");

            entity.Property(e => e.DetalleCompraId).HasColumnName("Detalle_CompraID");
            entity.Property(e => e.CodigoBarraMedicamentoId)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("Codigo_Barra_MedicamentoID");
            entity.Property(e => e.CodigoBarraProductoId)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("Codigo_Barra_ProductoID");
            entity.Property(e => e.CompraId).HasColumnName("CompraID");
            entity.Property(e => e.LoteMedicamentoId).HasColumnName("Lote_MedicamentoID");
            entity.Property(e => e.LoteProductoId).HasColumnName("Lote_ProductoID");

            entity.HasOne(d => d.Compra).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.CompraId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLESCOMPRAS_COMPRAS");

            entity.HasOne(d => d.LoteMedicamento).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.LoteMedicamentoId)
                .HasConstraintName("FK_DETALLESCOMPRAS_LOTEMED");

            entity.HasOne(d => d.LoteProducto).WithMany(p => p.DetallesCompras)
                .HasForeignKey(d => d.LoteProductoId)
                .HasConstraintName("FK_DETALLESCOMPRAS_LOTEPROD");
        });

        modelBuilder.Entity<DetallesFacturas>(entity =>
        {
            entity.HasKey(e => e.NroDetalleId);

            entity.ToTable("DETALLES_FACTURAS");

            entity.Property(e => e.NroDetalleId).HasColumnName("Nro_DetalleID");
            entity.Property(e => e.CoberturaId).HasColumnName("CoberturaID");
            entity.Property(e => e.DescuentoId).HasColumnName("DescuentoID");
            entity.Property(e => e.FacturaId).HasColumnName("FacturaID");
            entity.Property(e => e.MedicamentoId).HasColumnName("MedicamentoID");
            entity.Property(e => e.Precio).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");

            entity.HasOne(d => d.Cobertura).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.CoberturaId)
                .HasConstraintName("FK_DETFAC_COBERTURAS");

            entity.HasOne(d => d.Descuento).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.DescuentoId)
                .HasConstraintName("FK_DETFAC_DESCUENTOS");

            entity.HasOne(d => d.Factura).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.FacturaId)
                .HasConstraintName("FK_DETFAC_FACTURAS");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.MedicamentoId)
                .HasConstraintName("FK_DETFAC_MEDICAMENTOS");

            entity.HasOne(d => d.Producto).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.ProductoId)
                .HasConstraintName("FK_DETFAC_PRODUCTOS");
        });

        modelBuilder.Entity<DetallesRecetas>(entity =>
        {
            entity.HasKey(e => e.DetalleRecetaId);

            entity.ToTable("DETALLES_RECETAS");

            entity.Property(e => e.DetalleRecetaId).HasColumnName("Detalle_RecetaID");
            entity.Property(e => e.MedicamentoId).HasColumnName("MedicamentoID");
            entity.Property(e => e.RecetaId).HasColumnName("RecetaID");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.DetallesRecetas)
                .HasForeignKey(d => d.MedicamentoId)
                .HasConstraintName("FK_DETRECETAS_MEDICAMENTOS");

            entity.HasOne(d => d.Receta).WithMany(p => p.DetallesRecetas)
                .HasForeignKey(d => d.RecetaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETRECETAS_RECETAS");
        });

        modelBuilder.Entity<Doctores>(entity =>
        {
            entity.HasKey(e => e.DoctorId);

            entity.ToTable("DOCTORES");

            entity.Property(e => e.DoctorId).HasColumnName("DoctorID");
            entity.Property(e => e.ApellidoDoctor)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("Apellido_Doctor");
            entity.Property(e => e.EspecialidadId).HasColumnName("EspecialidadID");
            entity.Property(e => e.MatriculaDoctor)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Matricula_Doctor");
            entity.Property(e => e.NombreDoctor)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("Nombre_Doctor");

            entity.HasOne(d => d.Especialidad).WithMany(p => p.Doctores)
                .HasForeignKey(d => d.EspecialidadId)
                .HasConstraintName("FK_DOCTORES_ESPECIALIDADES");
        });

        modelBuilder.Entity<Empleados>(entity =>
        {
            entity.HasKey(e => e.EmpleadoId);

            entity.ToTable("EMPLEADOS");

            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.ApellidoEmpleado)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DireccionEmpleado)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DocumentoEmpleado)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmailEmpleado)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FechaNacimientoEmpleado).HasColumnName("Fecha_Nacimiento_Empleado");
            entity.Property(e => e.LocalidadId).HasColumnName("LocalidadID");
            entity.Property(e => e.NombreEmpleado)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoEmpleado)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TipoDocumentoId).HasColumnName("Tipo_DocumentoID");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.LocalidadId)
                .HasConstraintName("FK_EMPLEADOS_LOCALIDADES");

            entity.HasOne(d => d.TipoDocumento).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.TipoDocumentoId)
                .HasConstraintName("FK_EMPLEADOS_TIPOS_DOC");
        });

        modelBuilder.Entity<EmpleadosSucursales>(entity =>
        {
            entity.HasKey(e => e.EmpleadoSucursalId);

            entity.ToTable("EMPLEADOS_SUCURSALES");

            entity.Property(e => e.EmpleadoSucursalId).HasColumnName("Empleado_SucursalID");
            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.FechaFin)
                .HasPrecision(3)
                .HasColumnName("Fecha_Fin");
            entity.Property(e => e.FechaInicio)
                .HasPrecision(3)
                .HasColumnName("Fecha_Inicio");
            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");

            entity.HasOne(d => d.Empleado).WithMany(p => p.EmpleadosSucursales)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EMPSUC_EMPLEADOS");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.EmpleadosSucursales)
                .HasForeignKey(d => d.SucursalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EMPSUC_SUCURSALES");
        });

        modelBuilder.Entity<EspecialidadesMedicos>(entity =>
        {
            entity.HasKey(e => e.EspecialidadId);

            entity.ToTable("ESPECIALIDADES_MEDICOS");

            entity.Property(e => e.EspecialidadId).HasColumnName("EspecialidadID");
            entity.Property(e => e.NombreEspecialidad)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("Nombre_Especialidad");
        });

        modelBuilder.Entity<EstadosCoberturas>(entity =>
        {
            entity.HasKey(e => e.EstadoCoberturaId);

            entity.ToTable("ESTADOS_COBERTURAS");

            entity.Property(e => e.EstadoCoberturaId).HasColumnName("Estado_CoberturaID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Facturas>(entity =>
        {
            entity.HasKey(e => e.FacturaId);

            entity.ToTable("FACTURAS");

            entity.Property(e => e.FacturaId).HasColumnName("FacturaID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.FechaFacturacion)
                .HasPrecision(3)
                .HasColumnName("Fecha_Facturacion");
            entity.Property(e => e.MetodoPagoId).HasColumnName("Metodo_PagoID");
            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ClienteId)
                .HasConstraintName("FK_FACTURAS_CLIENTES");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.EmpleadoId)
                .HasConstraintName("FK_FACTURAS_EMPLEADOS");

            entity.HasOne(d => d.MetodoPago).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.MetodoPagoId)
                .HasConstraintName("FK_FACTURAS_METODOS_PAGO");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.SucursalId)
                .HasConstraintName("FK_FACTURAS_SUCURSALES");
        });

        modelBuilder.Entity<InventariosMedicamentos>(entity =>
        {
            entity.HasKey(e => e.InventarioMedicamentoId);

            entity.ToTable("INVENTARIOS_MEDICAMENTOS");

            entity.Property(e => e.InventarioMedicamentoId).HasColumnName("Inventario_MedicamentoID");
            entity.Property(e => e.MedicamentoId).HasColumnName("MedicamentoID");
            entity.Property(e => e.StockActual).HasColumnName("Stock_Actual");
            entity.Property(e => e.StockMinimo).HasColumnName("Stock_Minimo");
            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.InventariosMedicamentos)
                .HasForeignKey(d => d.MedicamentoId)
                .HasConstraintName("FK_INVMED_MEDICAMENTOS");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.InventariosMedicamentos)
                .HasForeignKey(d => d.SucursalId)
                .HasConstraintName("FK_INVMED_SUCURSAL");
        });

        modelBuilder.Entity<InventariosProductos>(entity =>
        {
            entity.ToTable("INVENTARIOS_PRODUCTOS");

            entity.Property(e => e.InventariosProductosId).HasColumnName("Inventarios_ProductosID");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.StockActual).HasColumnName("Stock_Actual");
            entity.Property(e => e.StockMinimo).HasColumnName("Stock_Minimo");
            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");

            entity.HasOne(d => d.Producto).WithMany(p => p.InventariosProductos)
                .HasForeignKey(d => d.ProductoId)
                .HasConstraintName("FK_INVPROD_PRODUCTOS");

            entity.HasOne(d => d.Sucursal).WithMany(p => p.InventariosProductos)
                .HasForeignKey(d => d.SucursalId)
                .HasConstraintName("FK_INVPROD_SUCURSAL");
        });

        modelBuilder.Entity<Localidades>(entity =>
        {
            entity.HasKey(e => e.LocalidadId);

            entity.ToTable("LOCALIDADES");

            entity.Property(e => e.LocalidadId).HasColumnName("LocalidadID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ProvinciaId).HasColumnName("ProvinciaID");

            entity.HasOne(d => d.Provincia).WithMany(p => p.Localidades)
                .HasForeignKey(d => d.ProvinciaId)
                .HasConstraintName("FK_LOCALIDADES_PROVINCIAS");
        });

        modelBuilder.Entity<LotesMedicamentos>(entity =>
        {
            entity.HasKey(e => e.LoteMedicamentoId);

            entity.ToTable("LOTES_MEDICAMENTOS");

            entity.Property(e => e.LoteMedicamentoId).HasColumnName("Lote_MedicamentoID");
            entity.Property(e => e.FechaElaboracion)
                .HasPrecision(3)
                .HasColumnName("Fecha_Elaboracion");
            entity.Property(e => e.FechaVencimiento)
                .HasPrecision(3)
                .HasColumnName("Fecha_Vencimiento");
            entity.Property(e => e.MedicamentoId).HasColumnName("MedicamentoID");

            entity.HasOne(d => d.Medicamento).WithMany(p => p.LotesMedicamentos)
                .HasForeignKey(d => d.MedicamentoId)
                .HasConstraintName("FK_LOTESMED_MEDICAMENTOS");
        });

        modelBuilder.Entity<LotesProductos>(entity =>
        {
            entity.HasKey(e => e.LoteProductoId);

            entity.ToTable("LOTES_PRODUCTOS");

            entity.Property(e => e.LoteProductoId).HasColumnName("Lote_ProductoID");
            entity.Property(e => e.FechaElaboracion)
                .HasPrecision(3)
                .HasColumnName("Fecha_Elaboracion");
            entity.Property(e => e.FechaVencimiento)
                .HasPrecision(3)
                .HasColumnName("Fecha_Vencimiento");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");

            entity.HasOne(d => d.Producto).WithMany(p => p.LotesProductos)
                .HasForeignKey(d => d.ProductoId)
                .HasConstraintName("FK_LOTESPROD_PRODUCTOS");
        });

        modelBuilder.Entity<Medicamentos>(entity =>
        {
            entity.HasKey(e => e.MedicamentoId);

            entity.ToTable("MEDICAMENTOS");

            entity.Property(e => e.MedicamentoId).HasColumnName("MedicamentoID");
            entity.Property(e => e.ClasificacionSuministroId).HasColumnName("Clasificacion_SuministroID");
            entity.Property(e => e.CodigoBarraMedicamentoId)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("Codigo_Barra_MedicamentoID");
            entity.Property(e => e.NombreMedicamento)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("Nombre_Medicamento");
            entity.Property(e => e.PrecioMedicamento)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("Precio_Medicamento");
            entity.Property(e => e.RestriccionId).HasColumnName("RestriccionID");
            entity.Property(e => e.TipoPresentacionId).HasColumnName("Tipo_PresentacionID");
            entity.Property(e => e.TipoSuministroId).HasColumnName("Tipo_SuministroID");
            entity.Property(e => e.UnidadMedidaId).HasColumnName("Unidad_MedidaID");

            entity.HasOne(d => d.ClasificacionSuministro).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.ClasificacionSuministroId)
                .HasConstraintName("FK_MEDICAMENTOS_CLASIFICACION");

            entity.HasOne(d => d.Restriccion).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.RestriccionId)
                .HasConstraintName("FK_MEDICAMENTOS_RESTRICCIONES");

            entity.HasOne(d => d.TipoPresentacion).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.TipoPresentacionId)
                .HasConstraintName("FK_MEDICAMENTOS_TIPO_PRESENTACION");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.TipoSuministroId)
                .HasConstraintName("FK_MEDICAMENTOS_TIPOS_SUMINISTRO");

            entity.HasOne(d => d.UnidadMedida).WithMany(p => p.Medicamentos)
                .HasForeignKey(d => d.UnidadMedidaId)
                .HasConstraintName("FK_MEDICAMENTOS_UNIDAD_MEDIDA");
        });

        modelBuilder.Entity<MetodosPagos>(entity =>
        {
            entity.HasKey(e => e.MetodoPagoId);

            entity.ToTable("METODOS_PAGOS");

            entity.Property(e => e.MetodoPagoId).HasColumnName("Metodo_PagoID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ObrasSociales>(entity =>
        {
            entity.HasKey(e => e.ObraSocialId);

            entity.ToTable("OBRAS_SOCIALES");

            entity.Property(e => e.ObraSocialId).HasColumnName("Obra_SocialID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Paises>(entity =>
        {
            entity.HasKey(e => e.PaisId);

            entity.ToTable("PAISES");

            entity.Property(e => e.PaisId).HasColumnName("PaisID");
            entity.Property(e => e.Descripciones)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PlanesObrasSociales>(entity =>
        {
            entity.HasKey(e => e.PlanObraSocialId);

            entity.ToTable("PLANES_OBRAS_SOCIALES");

            entity.Property(e => e.PlanObraSocialId).HasColumnName("Plan_Obra_SocialID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ObraSocialId).HasColumnName("Obra_SocialID");

            entity.HasOne(d => d.ObraSocial).WithMany(p => p.PlanesObrasSociales)
                .HasForeignKey(d => d.ObraSocialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PLAN_OBRA_OBRA_SOCIAL");
        });

        modelBuilder.Entity<Productos>(entity =>
        {
            entity.HasKey(e => e.ProductoId);

            entity.ToTable("PRODUCTOS");

            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.ClasificacionSuministroId).HasColumnName("Clasificacion_SuministroID");
            entity.Property(e => e.CodigoBarraProductoId)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("Codigo_Barra_ProductoID");
            entity.Property(e => e.NombreProducto)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("Nombre_Producto");
            entity.Property(e => e.PrecioProducto)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("Precio_Producto");
            entity.Property(e => e.TipoPresentacionId).HasColumnName("Tipo_PresentacionID");
            entity.Property(e => e.TipoSuministroId).HasColumnName("Tipo_SuministroID");
            entity.Property(e => e.UnidadMedidaId).HasColumnName("Unidad_MedidaID");

            entity.HasOne(d => d.ClasificacionSuministro).WithMany(p => p.Productos)
                .HasForeignKey(d => d.ClasificacionSuministroId)
                .HasConstraintName("FK_PRODUCTOS_CLASIFICACION");

            entity.HasOne(d => d.TipoPresentacion).WithMany(p => p.Productos)
                .HasForeignKey(d => d.TipoPresentacionId)
                .HasConstraintName("FK_PRODUCTOS_TIPO_PRESENTACION");

            entity.HasOne(d => d.TipoSuministro).WithMany(p => p.Productos)
                .HasForeignKey(d => d.TipoSuministroId)
                .HasConstraintName("FK_PRODUCTOS_TIPOS_SUMINISTRO");

            entity.HasOne(d => d.UnidadMedida).WithMany(p => p.Productos)
                .HasForeignKey(d => d.UnidadMedidaId)
                .HasConstraintName("FK_PRODUCTOS_UNIDAD_MEDIDA");
        });

        modelBuilder.Entity<Proveedores>(entity =>
        {
            entity.HasKey(e => e.ProveedorId);

            entity.ToTable("PROVEEDORES");

            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");
            entity.Property(e => e.Cuit)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CUIT");
            entity.Property(e => e.DireccionProveedor)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.EmailProveedor)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.RazonSocial)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoProveedor)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Provincias>(entity =>
        {
            entity.HasKey(e => e.ProvinciaId);

            entity.ToTable("PROVINCIAS");

            entity.Property(e => e.ProvinciaId).HasColumnName("ProvinciaID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.PaisId).HasColumnName("PaisID");

            entity.HasOne(d => d.Pais).WithMany(p => p.Provincias)
                .HasForeignKey(d => d.PaisId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROVINCIAS_PAISES");
        });

        modelBuilder.Entity<Recetas>(entity =>
        {
            entity.HasKey(e => e.RecetaId);

            entity.ToTable("RECETAS");

            entity.Property(e => e.RecetaId).HasColumnName("RecetaID");
            entity.Property(e => e.AfiliadoId).HasColumnName("AfiliadoID");
            entity.Property(e => e.DoctorId).HasColumnName("DoctorID");
            entity.Property(e => e.Fecha).HasPrecision(3);

            entity.HasOne(d => d.Afiliado).WithMany(p => p.Recetas)
                .HasForeignKey(d => d.AfiliadoId)
                .HasConstraintName("FK_RECETAS_AFILIADOS");

            entity.HasOne(d => d.Doctor).WithMany(p => p.Recetas)
                .HasForeignKey(d => d.DoctorId)
                .HasConstraintName("FK_RECETAS_DOCTORES");
        });

        modelBuilder.Entity<Repartidores>(entity =>
        {
            entity.HasKey(e => e.RepartidorId);

            entity.ToTable("REPARTIDORES");

            entity.Property(e => e.RepartidorId).HasColumnName("RepartidorID");
            entity.Property(e => e.ApellidoRepartidor)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.EmailRepartidor)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.NombreRepartidor)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoRepartidor)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Restricciones>(entity =>
        {
            entity.HasKey(e => e.RestriccionId);

            entity.ToTable("RESTRICCIONES");

            entity.Property(e => e.RestriccionId).HasColumnName("RestriccionID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Sucursales>(entity =>
        {
            entity.HasKey(e => e.SucursalId);

            entity.ToTable("SUCURSALES");

            entity.Property(e => e.SucursalId).HasColumnName("SucursalID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Direccion)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.LocalidadId).HasColumnName("LocalidadID");

            entity.HasOne(d => d.Localidad).WithMany(p => p.Sucursales)
                .HasForeignKey(d => d.LocalidadId)
                .HasConstraintName("FK_SUCURSALES_LOCALIDADES");
        });

        modelBuilder.Entity<TiposDescuentos>(entity =>
        {
            entity.HasKey(e => e.TipoDescuentoId);

            entity.ToTable("TIPOS_DESCUENTOS");

            entity.Property(e => e.TipoDescuentoId).HasColumnName("Tipo_DescuentoID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TiposDocumentos>(entity =>
        {
            entity.HasKey(e => e.TipoDocumentoId);

            entity.ToTable("TIPOS_DOCUMENTOS");

            entity.Property(e => e.TipoDocumentoId).HasColumnName("Tipo_DocumentoID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TiposPresentaciones>(entity =>
        {
            entity.HasKey(e => e.TipoPresentacionId);

            entity.ToTable("TIPOS_PRESENTACIONES");

            entity.Property(e => e.TipoPresentacionId).HasColumnName("Tipo_PresentacionID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TiposSuministros>(entity =>
        {
            entity.HasKey(e => e.TipoSuministroId);

            entity.ToTable("TIPOS_SUMINISTROS");

            entity.Property(e => e.TipoSuministroId).HasColumnName("Tipo_SuministroID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UnidadesMedidas>(entity =>
        {
            entity.HasKey(e => e.UnidadMedidaId);

            entity.ToTable("UNIDADES_MEDIDAS");

            entity.Property(e => e.UnidadMedidaId).HasColumnName("Unidad_MedidaID");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}