// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Domain.Models
{
    public partial class FarmaceuticaContext
    {
        private IFarmaceuticaContextProcedures _procedures;

        public virtual IFarmaceuticaContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FarmaceuticaContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFarmaceuticaContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class FarmaceuticaContextProcedures : IFarmaceuticaContextProcedures
    {
        private readonly FarmaceuticaContext _context;

        public FarmaceuticaContextProcedures(FarmaceuticaContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_ganancias_mensualesResult>> sp_ganancias_mensualesAsync(int? anio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_ganancias_mensualesResult>("EXEC @returnValue = [dbo].[sp_ganancias_mensuales] @anio = @anio", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_MPUsadosResult>> sp_MPUsadosAsync(int? anio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_MPUsadosResult>("EXEC @returnValue = [dbo].[sp_MPUsados] @anio = @anio", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_TraerTablasAsync(string empleado_dni, string proveedor, string repartidor, string sucursal, OutputParameter<int?> empleadoID, OutputParameter<int?> proveedorID, OutputParameter<int?> repartidorID, OutputParameter<int?> sucursalID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterempleadoID = new SqlParameter
            {
                ParameterName = "empleadoID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = empleadoID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterproveedorID = new SqlParameter
            {
                ParameterName = "proveedorID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = proveedorID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterrepartidorID = new SqlParameter
            {
                ParameterName = "repartidorID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = repartidorID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parametersucursalID = new SqlParameter
            {
                ParameterName = "sucursalID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = sucursalID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "empleado_dni",
                    Size = 100,
                    Value = empleado_dni ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "proveedor",
                    Size = 100,
                    Value = proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "repartidor",
                    Size = 100,
                    Value = repartidor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "sucursal",
                    Size = 100,
                    Value = sucursal ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterempleadoID,
                parameterproveedorID,
                parameterrepartidorID,
                parametersucursalID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_TraerTablas] @empleado_dni = @empleado_dni, @proveedor = @proveedor, @repartidor = @repartidor, @sucursal = @sucursal, @empleadoID = @empleadoID OUTPUT, @proveedorID = @proveedorID OUTPUT, @repartidorID = @repartidorID OUTPUT, @sucursalID = @sucursalID OUTPUT", sqlParameters, cancellationToken);

            empleadoID?.SetValue(parameterempleadoID.Value);
            proveedorID?.SetValue(parameterproveedorID.Value);
            repartidorID?.SetValue(parameterrepartidorID.Value);
            sucursalID?.SetValue(parametersucursalID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_TraerTablasDetalleAsync(string codigoBarraProducto, string codigoBarraMedicamento, int? loteMedicamento, int? loteProducto, OutputParameter<string> codigoBarraProductoReturn, OutputParameter<string> codigoBarraMedicamentoReturn, OutputParameter<int?> loteMedicamentoReturn, OutputParameter<int?> loteProductoReturn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parametercodigoBarraProductoReturn = new SqlParameter
            {
                ParameterName = "codigoBarraProductoReturn",
                Size = 100,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = codigoBarraProductoReturn?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parametercodigoBarraMedicamentoReturn = new SqlParameter
            {
                ParameterName = "codigoBarraMedicamentoReturn",
                Size = 100,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = codigoBarraMedicamentoReturn?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterloteMedicamentoReturn = new SqlParameter
            {
                ParameterName = "loteMedicamentoReturn",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = loteMedicamentoReturn?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterloteProductoReturn = new SqlParameter
            {
                ParameterName = "loteProductoReturn",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = loteProductoReturn?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "codigoBarraProducto",
                    Size = 100,
                    Value = codigoBarraProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "codigoBarraMedicamento",
                    Size = 100,
                    Value = codigoBarraMedicamento ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "loteMedicamento",
                    Value = loteMedicamento ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "loteProducto",
                    Value = loteProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parametercodigoBarraProductoReturn,
                parametercodigoBarraMedicamentoReturn,
                parameterloteMedicamentoReturn,
                parameterloteProductoReturn,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_TraerTablasDetalle] @codigoBarraProducto = @codigoBarraProducto, @codigoBarraMedicamento = @codigoBarraMedicamento, @loteMedicamento = @loteMedicamento, @loteProducto = @loteProducto, @codigoBarraProductoReturn = @codigoBarraProductoReturn OUTPUT, @codigoBarraMedicamentoReturn = @codigoBarraMedicamentoReturn OUTPUT, @loteMedicamentoReturn = @loteMedicamentoReturn OUTPUT, @loteProductoReturn = @loteProductoReturn OUTPUT", sqlParameters, cancellationToken);

            codigoBarraProductoReturn?.SetValue(parametercodigoBarraProductoReturn.Value);
            codigoBarraMedicamentoReturn?.SetValue(parametercodigoBarraMedicamentoReturn.Value);
            loteMedicamentoReturn?.SetValue(parameterloteMedicamentoReturn.Value);
            loteProductoReturn?.SetValue(parameterloteProductoReturn.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_VentasPorSucursalResult>> sp_VentasPorSucursalAsync(int? anio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "anio",
                    Value = anio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_VentasPorSucursalResult>("EXEC @returnValue = [dbo].[sp_VentasPorSucursal] @anio = @anio", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
