// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class InventariosProductos
{
    public int InventariosProductosId { get; set; }

    public int? SucursalId { get; set; }

    public int? ProductoId { get; set; }

    public int? StockMinimo { get; set; }

    public long? StockActual { get; set; }

    public bool? Activo { get; set; }

    public virtual Productos Producto { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}