// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Localidades
{
    public int LocalidadId { get; set; }

    public string Descripcion { get; set; }

    public int? ProvinciaId { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();

    public virtual ICollection<Descuentos> Descuentos { get; set; } = new List<Descuentos>();

    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();

    public virtual Provincias Provincia { get; set; }

    public virtual ICollection<Sucursales> Sucursales { get; set; } = new List<Sucursales>();
}