// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class LotesProductos
{
    public int LoteProductoId { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public DateTime? FechaElaboracion { get; set; }

    public long? Cantidad { get; set; }

    public int? ProductoId { get; set; }

    public virtual ICollection<DetallesCompras> DetallesCompras { get; set; } = new List<DetallesCompras>();

    public virtual Productos Producto { get; set; }
}