// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Medicamentos
{
    public int MedicamentoId { get; set; }

    public string CodigoBarraMedicamentoId { get; set; }

    public string NombreMedicamento { get; set; }

    public decimal? PrecioMedicamento { get; set; }

    public int? UnidadMedidaId { get; set; }

    public int? TipoPresentacionId { get; set; }

    public int? ClasificacionSuministroId { get; set; }

    public int? TipoSuministroId { get; set; }

    public int? RestriccionId { get; set; }

    public virtual ClasificacionesSuministros ClasificacionSuministro { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual ICollection<DetallesRecetas> DetallesRecetas { get; set; } = new List<DetallesRecetas>();

    public virtual ICollection<InventariosMedicamentos> InventariosMedicamentos { get; set; } = new List<InventariosMedicamentos>();

    public virtual ICollection<LotesMedicamentos> LotesMedicamentos { get; set; } = new List<LotesMedicamentos>();

    public virtual Restricciones Restriccion { get; set; }

    public virtual TiposPresentaciones TipoPresentacion { get; set; }

    public virtual TiposSuministros TipoSuministro { get; set; }

    public virtual UnidadesMedidas UnidadMedida { get; set; }
}