// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class MetodosPagos
{
    public int MetodoPagoId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();
}