// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class ObrasSociales
{
    public int ObraSocialId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Descuentos> Descuentos { get; set; } = new List<Descuentos>();

    public virtual ICollection<PlanesObrasSociales> PlanesObrasSociales { get; set; } = new List<PlanesObrasSociales>();
}