// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Paises
{
    public int PaisId { get; set; }

    public string Descripciones { get; set; }

    public virtual ICollection<Provincias> Provincias { get; set; } = new List<Provincias>();
}