// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Productos
{
    public int ProductoId { get; set; }

    public string CodigoBarraProductoId { get; set; }

    public string NombreProducto { get; set; }

    public decimal? PrecioProducto { get; set; }

    public int? TipoSuministroId { get; set; }

    public int? ClasificacionSuministroId { get; set; }

    public int? UnidadMedidaId { get; set; }

    public int? TipoPresentacionId { get; set; }

    public virtual ClasificacionesSuministros ClasificacionSuministro { get; set; }

    public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; } = new List<DetallesFacturas>();

    public virtual ICollection<InventariosProductos> InventariosProductos { get; set; } = new List<InventariosProductos>();

    public virtual ICollection<LotesProductos> LotesProductos { get; set; } = new List<LotesProductos>();

    public virtual TiposPresentaciones TipoPresentacion { get; set; }

    public virtual TiposSuministros TipoSuministro { get; set; }

    public virtual UnidadesMedidas UnidadMedida { get; set; }
}