// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Provincias
{
    public int ProvinciaId { get; set; }

    public int PaisId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Localidades> Localidades { get; set; } = new List<Localidades>();

    public virtual Paises Pais { get; set; }
}