// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Proveedores
{
    public int ProveedorId { get; set; }

    public string RazonSocial { get; set; }

    public string Cuit { get; set; }

    public string DireccionProveedor { get; set; }

    public string TelefonoProveedor { get; set; }

    public string EmailProveedor { get; set; }

    public int? Activo { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();
}