// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class Repartidores
{
    public int RepartidorId { get; set; }

    public string NombreRepartidor { get; set; }

    public string ApellidoRepartidor { get; set; }

    public string TelefonoRepartidor { get; set; }

    public string EmailRepartidor { get; set; }
    [JsonIgnore]
    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();
}