// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_ganancias_mensualesResult
    {
        public int? MES { get; set; }
        public int? AÑO { get; set; }
        [Column("IMPORTE", TypeName = "decimal(38,2)")]
        public decimal? IMPORTE { get; set; }
    }
}
