// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class sp_MPUsadosResult
    {
        [StringLength(200)]
        public string METODO_PAGO { get; set; }
        public int? CantidadMPUsado { get; set; }
        [Column("Porcentaje", TypeName = "decimal(5,2)")]
        public decimal? Porcentaje { get; set; }
    }
}
