// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Domain.Models;

public partial class Sucursales
{
    public int SucursalId { get; set; }

    public string Descripcion { get; set; }

    public string Direccion { get; set; }

    public int? LocalidadId { get; set; }
    [JsonIgnore]
    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();
    [JsonIgnore]
    public virtual ICollection<EmpleadosSucursales> EmpleadosSucursales { get; set; } = new List<EmpleadosSucursales>();
    [JsonIgnore]
    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();
    [JsonIgnore]
    public virtual ICollection<InventariosMedicamentos> InventariosMedicamentos { get; set; } = new List<InventariosMedicamentos>();
    [JsonIgnore]
    public virtual ICollection<InventariosProductos> InventariosProductos { get; set; } = new List<InventariosProductos>();
    [JsonIgnore]
    public virtual Localidades Localidad { get; set; }
}