// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Sucursales
{
    public int SucursalId { get; set; }

    public string Descripcion { get; set; }

    public string Direccion { get; set; }

    public int? LocalidadId { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();

    public virtual ICollection<EmpleadosSucursales> EmpleadosSucursales { get; set; } = new List<EmpleadosSucursales>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual ICollection<InventariosMedicamentos> InventariosMedicamentos { get; set; } = new List<InventariosMedicamentos>();

    public virtual ICollection<InventariosProductos> InventariosProductos { get; set; } = new List<InventariosProductos>();

    public virtual Localidades Localidad { get; set; }
}