// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class TiposDescuentos
{
    public int TipoDescuentoId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Descuentos> Descuentos { get; set; } = new List<Descuentos>();
}