// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class TiposSuministros
{
    public int TipoSuministroId { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Descuentos> Descuentos { get; set; } = new List<Descuentos>();

    public virtual ICollection<Medicamentos> Medicamentos { get; set; } = new List<Medicamentos>();

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}