// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class VwMedicamentoTop
{
    public string Nombre { get; set; }

    public string CodigoDeBarra { get; set; }

    public decimal? PrecioVenta { get; set; }

    public string Sucursal { get; set; }

    public int? CantidadVendidaTotal { get; set; }
}