// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class VwMpusado
{
    public string MetodoPago { get; set; }

    public int? Cantidad { get; set; }
}