// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class VwVentasPorSucursal
{
    public string Sucursal { get; set; }

    public int? CantidadVentas { get; set; }
}