
/*
  Script: CREATE TABLE con FKs INLINE y GO.
  Ordenado para ejecución directa en SQL Server.
--  Sólo tablas y relaciones (PK + FK). No índices adicionales, no triggers, no vistas.
----*/

--create database Farmaceutica
--go

--Use Farmaceutica
--go

-- 1. TIPOS_DOCUMENTOS
CREATE TABLE TIPOS_DOCUMENTOS (
    Tipo_DocumentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPOS_DOCUMENTOS PRIMARY KEY,
    Descripcion VARCHAR(250) NULL
);
GO

-- 2. PAISES
CREATE TABLE PAISES (
    PaisID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PAISES PRIMARY KEY,
    Descripciones VARCHAR(200) NULL
);
GO

-- 3. PROVINCIAS (FK -> PAISES)
CREATE TABLE PROVINCIAS (
    ProvinciaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROVINCIAS PRIMARY KEY,
    PaisID INT NOT NULL,
    Descripcion VARCHAR(200) NULL,
    CONSTRAINT FK_PROVINCIAS_PAISES FOREIGN KEY (PaisID) REFERENCES PAISES(PaisID)
);
GO

-- 4. LOCALIDADES (FK -> PROVINCIAS)
CREATE TABLE LOCALIDADES (
    LocalidadID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LOCALIDADES PRIMARY KEY,
    Descripcion VARCHAR(250) NULL,
    ProvinciaID INT NULL,
    CONSTRAINT FK_LOCALIDADES_PROVINCIAS FOREIGN KEY (ProvinciaID) REFERENCES PROVINCIAS(ProvinciaID)
);
GO

-- 5. TIPOS_PRESENTACIONES
CREATE TABLE TIPOS_PRESENTACIONES (
    Tipo_PresentacionID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPOS_PRESENTACIONES PRIMARY KEY,
    Descripcion VARCHAR(200) NULL
);
GO

-- 6. UNIDADES_MEDIDAS
CREATE TABLE UNIDADES_MEDIDAS (
    Unidad_MedidaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_UNIDADES_MEDIDAS PRIMARY KEY,
    Descripcion VARCHAR(200) NULL
);
GO

-- 7. TIPOS_SUMINISTROS
CREATE TABLE TIPOS_SUMINISTROS (
    Tipo_SuministroID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPOS_SUMINISTROS PRIMARY KEY,
    Descripcion VARCHAR(200) NULL
);
GO

-- 8. CLASIFICACIONES_SUMINISTROS
CREATE TABLE CLASIFICACIONES_SUMINISTROS (
    Clasificacion_SuministroID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLASIFICACIONES_SUMINISTROS PRIMARY KEY,
    Descripcion VARCHAR(200) NULL
);
GO

-- 9. RESTRICCIONES
CREATE TABLE RESTRICCIONES (
    RestriccionID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_RESTRICCIONES PRIMARY KEY,
    Descripcion VARCHAR(250) NULL
);
GO

-- 10. TIPOS_DESCUENTOS
CREATE TABLE TIPOS_DESCUENTOS (
    Tipo_DescuentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPOS_DESCUENTOS PRIMARY KEY,
    Descripcion VARCHAR(250) NULL
);
GO

-- 11. METODOS_PAGOS
CREATE TABLE METODOS_PAGOS (
    Metodo_PagoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_METODOS_PAGOS PRIMARY KEY,
    Descripcion VARCHAR(200) NULL
);
GO

-- 12. ESPECIALIDADES_MEDICOS
CREATE TABLE ESPECIALIDADES_MEDICOS (
    EspecialidadID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESPECIALIDADES_MEDICOS PRIMARY KEY,
    Nombre_Especialidad VARCHAR(250) NULL
);
GO

-- 13. OBRAS_SOCIALES
CREATE TABLE OBRAS_SOCIALES (
    Obra_SocialID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_OBRAS_SOCIALES PRIMARY KEY,
    Descripcion VARCHAR(250) NULL
);
GO

-- 14. PLANES_OBRAS_SOCIALES (FK -> OBRAS_SOCIALES)
CREATE TABLE PLANES_OBRAS_SOCIALES (
    Plan_Obra_SocialID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PLANES_OBRAS_SOCIALES PRIMARY KEY,
    Descripcion VARCHAR(250) NULL,
    Obra_SocialID INT NOT NULL,
    CONSTRAINT FK_PLAN_OBRA_OBRA_SOCIAL FOREIGN KEY (Obra_SocialID) REFERENCES OBRAS_SOCIALES(Obra_SocialID)
);
GO

-- 15. PROVEEDORES
CREATE TABLE PROVEEDORES (
    ProveedorID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROVEEDORES PRIMARY KEY,
    RazonSocial VARCHAR(250) NULL,
    CUIT VARCHAR(50) NULL,
    DireccionProveedor VARCHAR(500) NULL,
    TelefonoProveedor VARCHAR(50) NULL,
    EmailProveedor VARCHAR(250) NULL
);
GO

-- 16. REPARTIDORES
CREATE TABLE REPARTIDORES (
    RepartidorID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_REPARTIDORES PRIMARY KEY,
    NombreRepartidor VARCHAR(250) NULL,
    ApellidoRepartidor VARCHAR(250) NULL,
    TelefonoRepartidor VARCHAR(50) NULL,
    EmailRepartidor VARCHAR(250) NULL
);
GO

-- 17. SUCURSALES (FK -> LOCALIDADES)
CREATE TABLE SUCURSALES (
    SucursalID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SUCURSALES PRIMARY KEY,
    Descripcion VARCHAR(250) NULL,
    Direccion VARCHAR(500) NULL,
    LocalidadID INT NULL,
    CONSTRAINT FK_SUCURSALES_LOCALIDADES FOREIGN KEY (LocalidadID) REFERENCES LOCALIDADES(LocalidadID)
);
GO

-- 18. PRODUCTOS (FKs -> TIPOS_SUMINISTROS, CLASIFICACIONES_SUMINISTROS, UNIDADES_MEDIDAS, TIPOS_PRESENTACIONES)
CREATE TABLE PRODUCTOS (
    ProductoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PRODUCTOS PRIMARY KEY,
    Codigo_Barra_ProductoID VARCHAR(150) NULL,
    Nombre_Producto VARCHAR(400) NULL,
    Precio_Producto DECIMAL(12,2) NULL,
    Tipo_SuministroID INT NULL,
    Clasificacion_SuministroID INT NULL,
    Unidad_MedidaID INT NULL,
    Tipo_PresentacionID INT NULL,
    CONSTRAINT FK_PRODUCTOS_TIPOS_SUMINISTRO FOREIGN KEY (Tipo_SuministroID) REFERENCES TIPOS_SUMINISTROS(Tipo_SuministroID),
    CONSTRAINT FK_PRODUCTOS_CLASIFICACION FOREIGN KEY (Clasificacion_SuministroID) REFERENCES CLASIFICACIONES_SUMINISTROS(Clasificacion_SuministroID),
    CONSTRAINT FK_PRODUCTOS_UNIDAD_MEDIDA FOREIGN KEY (Unidad_MedidaID) REFERENCES UNIDADES_MEDIDAS(Unidad_MedidaID),
    CONSTRAINT FK_PRODUCTOS_TIPO_PRESENTACION FOREIGN KEY (Tipo_PresentacionID) REFERENCES TIPOS_PRESENTACIONES(Tipo_PresentacionID)
);
GO

-- 19. MEDICAMENTOS (FKs -> UNIDADES_MEDIDAS, TIPOS_PRESENTACIONES, CLASIFICACIONES_SUMINISTROS, TIPOS_SUMINISTROS, RESTRICCIONES)
CREATE TABLE MEDICAMENTOS (
    MedicamentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY,
    Codigo_Barra_MedicamentoID VARCHAR(150) NULL,
    Nombre_Medicamento VARCHAR(400) NULL,
    Precio_Medicamento DECIMAL(12,2) NULL,
    Unidad_MedidaID INT NULL,
    Tipo_PresentacionID INT NULL,
    Clasificacion_SuministroID INT NULL,
    Tipo_SuministroID INT NULL,
    RestriccionID INT NULL,
    CONSTRAINT FK_MEDICAMENTOS_UNIDAD_MEDIDA FOREIGN KEY (Unidad_MedidaID) REFERENCES UNIDADES_MEDIDAS(Unidad_MedidaID),
    CONSTRAINT FK_MEDICAMENTOS_TIPO_PRESENTACION FOREIGN KEY (Tipo_PresentacionID) REFERENCES TIPOS_PRESENTACIONES(Tipo_PresentacionID),
    CONSTRAINT FK_MEDICAMENTOS_CLASIFICACION FOREIGN KEY (Clasificacion_SuministroID) REFERENCES CLASIFICACIONES_SUMINISTROS(Clasificacion_SuministroID),
    CONSTRAINT FK_MEDICAMENTOS_TIPOS_SUMINISTRO FOREIGN KEY (Tipo_SuministroID) REFERENCES TIPOS_SUMINISTROS(Tipo_SuministroID),
    CONSTRAINT FK_MEDICAMENTOS_RESTRICCIONES FOREIGN KEY (RestriccionID) REFERENCES RESTRICCIONES(RestriccionID)
);
GO

-- 20. LOTES_PRODUCTOS (FK -> PRODUCTOS)
CREATE TABLE LOTES_PRODUCTOS (
    Lote_ProductoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LOTES_PRODUCTOS PRIMARY KEY,
    Fecha_Vencimiento DATETIME2(3) NULL,
    Fecha_Elaboracion DATETIME2(3) NULL,
    Cantidad BIGINT NULL,
    ProductoID INT NULL,
    CONSTRAINT FK_LOTESPROD_PRODUCTOS FOREIGN KEY (ProductoID) REFERENCES PRODUCTOS(ProductoID)
);
GO

-- 21. LOTES_MEDICAMENTOS (FK -> MEDICAMENTOS)
CREATE TABLE LOTES_MEDICAMENTOS (
    Lote_MedicamentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LOTES_MEDICAMENTOS PRIMARY KEY,
    MedicamentoID INT NULL,
    Fecha_Vencimiento DATETIME2(3) NULL,
    Fecha_Elaboracion DATETIME2(3) NULL,
    Cantidad BIGINT NULL,
    CONSTRAINT FK_LOTESMED_MEDICAMENTOS FOREIGN KEY (MedicamentoID) REFERENCES MEDICAMENTOS(MedicamentoID)
);
GO

-- 22. CLIENTES (FKs -> TIPOS_DOCUMENTOS, LOCALIDADES)
CREATE TABLE CLIENTES (
    ClienteID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLIENTES PRIMARY KEY,
    NombreCliente VARCHAR(250) NULL,
    ApellidoCliente VARCHAR(250) NULL,
    Fecha_Nacimiento_Cliente DATE NULL,
    TelefonoCliente VARCHAR(50) NULL,
    Tipo_DocumentoID INT NULL,
    DireccionCliente VARCHAR(500) NULL,
    LocalidadID INT NULL,
    EmailCliente VARCHAR(250) NULL,
    DocumentoCliente VARCHAR(100) NULL,
    CONSTRAINT FK_CLIENTES_TIPOS_DOCUMENTOS FOREIGN KEY (Tipo_DocumentoID) REFERENCES TIPOS_DOCUMENTOS(Tipo_DocumentoID),
    CONSTRAINT FK_CLIENTES_LOCALIDADES FOREIGN KEY (LocalidadID) REFERENCES LOCALIDADES(LocalidadID)
);
GO

-- 23. EMPLEADOS (FKs -> TIPOS_DOCUMENTOS, LOCALIDADES)
CREATE TABLE EMPLEADOS (
    EmpleadoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
    NombreEmpleado VARCHAR(250) NULL,
    ApellidoEmpleado VARCHAR(250) NULL,
    Fecha_Nacimiento_Empleado DATE NULL,
    DireccionEmpleado VARCHAR(500) NULL,
    TelefonoEmpleado VARCHAR(50) NULL,
    EmailEmpleado VARCHAR(250) NULL,
    LocalidadID INT NULL,
    Tipo_DocumentoID INT NULL,
    DocumentoEmpleado VARCHAR(100) NULL,
    CONSTRAINT FK_EMPLEADOS_TIPOS_DOC FOREIGN KEY (Tipo_DocumentoID) REFERENCES TIPOS_DOCUMENTOS(Tipo_DocumentoID),
    CONSTRAINT FK_EMPLEADOS_LOCALIDADES FOREIGN KEY (LocalidadID) REFERENCES LOCALIDADES(LocalidadID)
);
GO

-- 24. AFILIADOS (FKs -> PLANES_OBRAS_SOCIALES, CLIENTES)
CREATE TABLE AFILIADOS (
    AfiliadoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AFILIADOS PRIMARY KEY,
    Plan_Obra_SocialID INT NOT NULL,
    ClienteID INT NOT NULL,
    CONSTRAINT FK_AFILIADOS_PLAN_OBRA FOREIGN KEY (Plan_Obra_SocialID) REFERENCES PLANES_OBRAS_SOCIALES(Plan_Obra_SocialID),
    CONSTRAINT FK_AFILIADOS_CLIENTES FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID)
);
GO

-- 25. DOCTORES (FK -> ESPECIALIDADES_MEDICOS)
CREATE TABLE DOCTORES (
    DoctorID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DOCTORES PRIMARY KEY,
    Nombre_Doctor VARCHAR(250) NULL,
    Apellido_Doctor VARCHAR(250) NULL,
    Matricula_Doctor VARCHAR(100) NULL,
    EspecialidadID INT NULL,
    CONSTRAINT FK_DOCTORES_ESPECIALIDADES FOREIGN KEY (EspecialidadID) REFERENCES ESPECIALIDADES_MEDICOS(EspecialidadID)
);
GO

-- 26. RECETAS (FKs -> AFILIADOS, DOCTORES)
CREATE TABLE RECETAS (
    RecetaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_RECETAS PRIMARY KEY,
    Fecha DATETIME2(3) NULL,
    AfiliadoID INT NULL,
    DoctorID INT NULL,
    CONSTRAINT FK_RECETAS_AFILIADOS FOREIGN KEY (AfiliadoID) REFERENCES AFILIADOS(AfiliadoID),
    CONSTRAINT FK_RECETAS_DOCTORES FOREIGN KEY (DoctorID) REFERENCES DOCTORES(DoctorID)
);
GO

-- 27. ESTADOS_COBERTURAS
CREATE TABLE ESTADOS_COBERTURAS (
    Estado_CoberturaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESTADOS_COBERTURAS PRIMARY KEY,
    Descripcion VARCHAR(250) NULL
);
GO

-- 28. COBERTURAS (FKs -> ESTADOS_COBERTURAS, AFILIADOS, RECETAS)
CREATE TABLE COBERTURAS (
    CoberturaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COBERTURAS PRIMARY KEY,
    Validacion_Obra_Social BIT NOT NULL DEFAULT 0,
    Estado_CoberturaID INT NULL,
    AfiliadoID INT NULL,
    RecetaID INT NULL,
    CONSTRAINT FK_COBERTURAS_ESTADOS FOREIGN KEY (Estado_CoberturaID) REFERENCES ESTADOS_COBERTURAS(Estado_CoberturaID),
    CONSTRAINT FK_COBERTURAS_AFILIADOS FOREIGN KEY (AfiliadoID) REFERENCES AFILIADOS(AfiliadoID),
    CONSTRAINT FK_COBERTURAS_RECETAS FOREIGN KEY (RecetaID) REFERENCES RECETAS(RecetaID)
);
GO

-- 29. DETALLES_RECETAS (FKs -> RECETAS, MEDICAMENTOS)
CREATE TABLE DETALLES_RECETAS (
    Detalle_RecetaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DETALLES_RECETAS PRIMARY KEY,
    RecetaID INT NOT NULL,
    Cantidad INT NOT NULL,
    MedicamentoID INT NULL,
    CONSTRAINT FK_DETRECETAS_RECETAS FOREIGN KEY (RecetaID) REFERENCES RECETAS(RecetaID),
    CONSTRAINT FK_DETRECETAS_MEDICAMENTOS FOREIGN KEY (MedicamentoID) REFERENCES MEDICAMENTOS(MedicamentoID)
);
GO

-- 30. DESCUENTOS (FKs opcionales)
CREATE TABLE DESCUENTOS (
    DescuentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DESCUENTOS PRIMARY KEY,
    LocalidadID INT NULL,
    Fecha_Descuento DATETIME2(3) NULL,
    Tipo_SuministroID INT NULL,
    Obra_SocialID INT NULL,
    Porcentaje_Descuento DECIMAL(12,2) NULL,
    Tipo_DescuentoID INT NULL,
    CONSTRAINT FK_DESCUENTOS_TIPOSDESCUENTO FOREIGN KEY (Tipo_DescuentoID) REFERENCES TIPOS_DESCUENTOS(Tipo_DescuentoID),
    CONSTRAINT FK_DESCUENTOS_TIPOSUMINISTRO FOREIGN KEY (Tipo_SuministroID) REFERENCES TIPOS_SUMINISTROS(Tipo_SuministroID),
    CONSTRAINT FK_DESCUENTOS_OBRAS_SOCIALES FOREIGN KEY (Obra_SocialID) REFERENCES OBRAS_SOCIALES(Obra_SocialID),
    CONSTRAINT FK_DESCUENTOS_LOCALIDADES FOREIGN KEY (LocalidadID) REFERENCES LOCALIDADES(LocalidadID)
);
GO

-- 31. FACTURAS (FKs -> EMPLEADOS, CLIENTES, SUCURSALES, METODOS_PAGOS)
CREATE TABLE FACTURAS (
    FacturaID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_FACTURAS PRIMARY KEY,
    Fecha_Facturacion DATETIME2(3) NULL,
    EmpleadoID INT NULL,
    ClienteID INT NULL,
    SucursalID INT NULL,
    Metodo_PagoID INT NULL,
    CONSTRAINT FK_FACTURAS_EMPLEADOS FOREIGN KEY (EmpleadoID) REFERENCES EMPLEADOS(EmpleadoID),
    CONSTRAINT FK_FACTURAS_CLIENTES FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID),
    CONSTRAINT FK_FACTURAS_SUCURSALES FOREIGN KEY (SucursalID) REFERENCES SUCURSALES(SucursalID),
    CONSTRAINT FK_FACTURAS_METODOS_PAGO FOREIGN KEY (Metodo_PagoID) REFERENCES METODOS_PAGOS(Metodo_PagoID)
);
GO

-- 32. DETALLES_FACTURAS (FKs -> DESCUENTOS, PRODUCTOS, MEDICAMENTOS, COBERTURAS, FACTURAS)
CREATE TABLE DETALLES_FACTURAS (
    Nro_DetalleID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DETALLES_FACTURAS PRIMARY KEY,
    DescuentoID INT NULL,
    ProductoID INT NULL,
    MedicamentoID INT NULL,
    Cantidad INT NOT NULL,
    Precio DECIMAL(12,2) NULL,
    CoberturaID INT NULL,
    FacturaID INT NULL,
    CONSTRAINT FK_DETFAC_DESCUENTOS FOREIGN KEY (DescuentoID) REFERENCES DESCUENTOS(DescuentoID),
    CONSTRAINT FK_DETFAC_PRODUCTOS FOREIGN KEY (ProductoID) REFERENCES PRODUCTOS(ProductoID),
    CONSTRAINT FK_DETFAC_MEDICAMENTOS FOREIGN KEY (MedicamentoID) REFERENCES MEDICAMENTOS(MedicamentoID),
    CONSTRAINT FK_DETFAC_COBERTURAS FOREIGN KEY (CoberturaID) REFERENCES COBERTURAS(CoberturaID),
    CONSTRAINT FK_DETFAC_FACTURAS FOREIGN KEY (FacturaID) REFERENCES FACTURAS(FacturaID)
);
GO

-- 33. COMPRAS (FKs -> PROVEEDORES, REPARTIDORES, SUCURSALES, EMPLEADOS)
CREATE TABLE COMPRAS (
    CompraID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COMPRAS PRIMARY KEY,
    Fecha_Compra DATETIME2(3) NULL,
    EmpleadoID INT NULL,
    ProveedorID INT NULL,
    RepartidorID INT NULL,
    SucursalID INT NULL,
    CONSTRAINT FK_COMPRAS_PROVEEDORES FOREIGN KEY (ProveedorID) REFERENCES PROVEEDORES(ProveedorID),
    CONSTRAINT FK_COMPRAS_REPARTIDORES FOREIGN KEY (RepartidorID) REFERENCES REPARTIDORES(RepartidorID),
    CONSTRAINT FK_COMPRAS_SUCURSALES FOREIGN KEY (SucursalID) REFERENCES SUCURSALES(SucursalID),
    CONSTRAINT FK_COMPRAS_EMPLEADOS FOREIGN KEY (EmpleadoID) REFERENCES EMPLEADOS(EmpleadoID)
);
GO

-- 34. DETALLES_COMPRAS (FKs -> COMPRAS, LOTES_PRODUCTOS, LOTES_MEDICAMENTOS)
CREATE TABLE DETALLES_COMPRAS (
    Detalle_CompraID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DETALLES_COMPRAS PRIMARY KEY,
    CompraID INT NOT NULL,
    Lote_ProductoID INT NULL,
    Codigo_Barra_MedicamentoID VARCHAR(150) NULL,
    Codigo_Barra_ProductoID VARCHAR(150) NULL,
    Cantidad INT NOT NULL,
    Lote_MedicamentoID INT NULL,
    CONSTRAINT FK_DETALLESCOMPRAS_COMPRAS FOREIGN KEY (CompraID) REFERENCES COMPRAS(CompraID),
    CONSTRAINT FK_DETALLESCOMPRAS_LOTEPROD FOREIGN KEY (Lote_ProductoID) REFERENCES LOTES_PRODUCTOS(Lote_ProductoID),
    CONSTRAINT FK_DETALLESCOMPRAS_LOTEMED FOREIGN KEY (Lote_MedicamentoID) REFERENCES LOTES_MEDICAMENTOS(Lote_MedicamentoID)
);
GO

-- 35. INVENTARIOS_PRODUCTOS (FKs -> SUCURSALES, PRODUCTOS)
CREATE TABLE INVENTARIOS_PRODUCTOS (
    Inventarios_ProductosID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_INVENTARIOS_PRODUCTOS PRIMARY KEY,
    SucursalID INT NULL,
    ProductoID INT NULL,
    Stock_Minimo INT NULL,
    Stock_Actual BIGINT NULL,
    CONSTRAINT FK_INVPROD_SUCURSAL FOREIGN KEY (SucursalID) REFERENCES SUCURSALES(SucursalID),
    CONSTRAINT FK_INVPROD_PRODUCTOS FOREIGN KEY (ProductoID) REFERENCES PRODUCTOS(ProductoID)
);
GO

-- 36. INVENTARIOS_MEDICAMENTOS (FKs -> SUCURSALES, MEDICAMENTOS)
CREATE TABLE INVENTARIOS_MEDICAMENTOS (
    Inventario_MedicamentoID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_INVENTARIOS_MEDICAMENTOS PRIMARY KEY,
    SucursalID INT NULL,
    MedicamentoID INT NULL,
    Stock_Minimo INT NULL,
    Stock_Actual BIGINT NULL,
    CONSTRAINT FK_INVMED_SUCURSAL FOREIGN KEY (SucursalID) REFERENCES SUCURSALES(SucursalID),
    CONSTRAINT FK_INVMED_MEDICAMENTOS FOREIGN KEY (MedicamentoID) REFERENCES MEDICAMENTOS(MedicamentoID)
);
GO

-- 37. EMPLEADOS_SUCURSALES (FKs -> EMPLEADOS, SUCURSALES)
CREATE TABLE EMPLEADOS_SUCURSALES (
    Empleado_SucursalID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EMPLEADOS_SUCURSALES PRIMARY KEY,
    EmpleadoID INT NOT NULL,
    SucursalID INT NOT NULL,
    Fecha_Inicio DATETIME2(3) NULL,
    Fecha_Fin DATETIME2(3) NULL,
    CONSTRAINT FK_EMPSUC_EMPLEADOS FOREIGN KEY (EmpleadoID) REFERENCES EMPLEADOS(EmpleadoID),
    CONSTRAINT FK_EMPSUC_SUCURSALES FOREIGN KEY (SucursalID) REFERENCES SUCURSALES(SucursalID)
);
GO


alter table COMPRAS
add activo bit 
go

alter table DETALLES_COMPRAS
add activo bit 
go

alter table PROVEEDORES
add activo bit
go

alter table MEDICAMENTOS
add activo bit
go

alter table PRODUCTOS
add activo bit
go

alter table INVENTARIOS_MEDICAMENTOS
add activo bit
go

alter table INVENTARIOS_PRODUCTOS
add activo bit
go



create view [dbo].[VwMedicamentoTop]
as
SELECT TOP (3) m.Nombre_Medicamento AS Nombre, m.Codigo_Barra_MedicamentoID AS CodigoDeBarra
, df.Precio AS PrecioVenta, s.Descripcion AS Sucursal
, SUM(df.Cantidad) AS CantidadVendidaTotal
FROM     dbo.DETALLES_FACTURAS AS df INNER JOIN
                  dbo.FACTURAS AS f ON f.FacturaID = df.FacturaID INNER JOIN
                  dbo.MEDICAMENTOS AS m ON m.MedicamentoID = df.MedicamentoID INNER JOIN
                  dbo.SUCURSALES AS s ON s.SucursalID = f.SucursalID
WHERE  (df.ProductoID IS NULL)
GROUP BY m.Nombre_Medicamento, m.Codigo_Barra_MedicamentoID, df.Precio, s.Descripcion
ORDER BY CantidadVendidaTotal DESC
go

create view [dbo].[VwProductoTop]
as
SELECT TOP (3) p.Nombre_Producto AS Nombre, p.Codigo_Barra_ProductoID AS CodigoDeBarra
, df.Precio AS PrecioVenta, s.Descripcion AS Sucursal
, SUM(df.Cantidad) AS CantidadVendidaTotal
FROM     dbo.DETALLES_FACTURAS AS df INNER JOIN
                  dbo.FACTURAS AS f ON f.FacturaID = df.FacturaID INNER JOIN
                  dbo.PRODUCTOS AS p ON p.ProductoID = df.ProductoID INNER JOIN
                  dbo.SUCURSALES AS s ON s.SucursalID = f.SucursalID
WHERE  (df.MedicamentoID IS NULL)
GROUP BY p.Nombre_Producto, p.Codigo_Barra_ProductoID, df.Precio, s.Descripcion
ORDER BY CantidadVendidaTotal DESC
go




create procedure sp_TraerTablas
    @empleado_dni varchar(100) ,
    @proveedor varchar(100) ,
    @repartidor varchar(100) ,
    @sucursal varchar(100),
    @empleadoID int output,
    @proveedorID int output,
    @repartidorID int output,
    @sucursalID int output
as
begin
    set @empleadoID  = (SELECT EmpleadoID FROM EMPLEADOS WHERE DocumentoEmpleado = @empleado_dni)
    set @proveedorID  = (SELECT ProveedorID FROM PROVEEDORES WHERE RazonSocial = @proveedor);
    set @repartidorID  = (SELECT RepartidorID FROM REPARTIDORES WHERE EmailRepartidor = @repartidor);
    set @sucursalID  = (SELECT SucursalID FROM SUCURSALES WHERE Descripcion = @sucursal);
end
go


create procedure sp_TraerTablasDetalle
    @codigoBarraProducto varchar(100),
    @codigoBarraMedicamento varchar(100),
    @loteMedicamento int,
    @loteProducto int,
    @codigoBarraProductoReturn varchar(100) output,
    @codigoBarraMedicamentoReturn varchar(100)output,
    @loteMedicamentoReturn int output,
    @loteProductoReturn int output
as 
begin
    set @codigoBarraMedicamentoReturn = (SELECT Codigo_Barra_MedicamentoID FROM MEDICAMENTOS WHERE Codigo_Barra_MedicamentoID = @codigoBarraMedicamento)
    set @codigoBarraProductoReturn = (SELECT Codigo_Barra_ProductoID FROM PRODUCTOS WHERE Codigo_Barra_ProductoID = @codigoBarraProducto)
    set @loteProductoReturn = (SELECT Lote_ProductoID FROM LOTES_PRODUCTOS WHERE Lote_ProductoID = @loteProducto)
    set @loteMedicamentoReturn = (SELECT Lote_MedicamentoID FROM LOTES_MEDICAMENTOS WHERE Lote_MedicamentoID = @loteMedicamento)
end
go

create procedure sp_ganancias_mensuales
    @anio int
as
begin
    select MONTH(f.Fecha_Facturacion) 'MES',
            YEAR(f.Fecha_Facturacion) 'AÑO',
            SUM(df.Precio*df.Cantidad) 'IMPORTE'
    from DETALLES_FACTURAS df
    JOIN FACTURAS f on f.FacturaID = df.FacturaID
    WHERE YEAR(f.Fecha_Facturacion) = @anio
    GROUP BY MONTH(f.Fecha_Facturacion), YEAR(f.Fecha_Facturacion)
    ORDER BY MES desc
end
go



CREATE PROCEDURE [dbo].[sp_VentasPorSucursal]
    @anio INT
AS
BEGIN
    ;WITH Totales AS (
        SELECT COUNT(*) AS TotalFacturas
        FROM FACTURAS
        WHERE YEAR(Fecha_Facturacion) = @anio
    )
    SELECT 
        s.Descripcion AS SUCURSAL,
        COUNT(f.FacturaID) AS CantidadSucursal,
        CAST(COUNT(f.FacturaID) * 100.0 / t.TotalFacturas AS DECIMAL(5,2)) AS Porcentaje
    FROM FACTURAS f
    JOIN SUCURSALES s ON f.SucursalID = s.SucursalID
    CROSS JOIN Totales t
    WHERE YEAR(f.Fecha_Facturacion) = @anio
    GROUP BY s.Descripcion, t.TotalFacturas
    ORDER BY Porcentaje DESC;
END
GO

CREATE PROCEDURE [dbo].[sp_MPUsados]
    @anio INT
AS
BEGIN
    ;WITH Totales AS (
        SELECT COUNT(*) AS TotalFacturas
        FROM FACTURAS
        WHERE YEAR(Fecha_Facturacion) = @anio
    )
    SELECT 
        mp.Descripcion 'METODO_PAGO',
        COUNT(f.FacturaID) AS CantidadMPUsado,
        CAST(COUNT(f.FacturaID) * 100.0 / t.TotalFacturas AS DECIMAL(5,2)) AS Porcentaje
    FROM FACTURAS f
    JOIN METODOS_PAGOS mp ON f.Metodo_PagoID= mp.Metodo_PagoID
    CROSS JOIN Totales t
    WHERE YEAR(f.Fecha_Facturacion) = @anio
    GROUP BY mp.Descripcion, t.TotalFacturas
    ORDER BY Porcentaje DESC;
END
GO

CREATE TRIGGER trg_Compra_ActualizarStock
ON detalles_compras
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE inv
    SET inv.Stock_Actual = inv.Stock_Actual + i.Cantidad
    FROM inserted i
    INNER JOIN MEDICAMENTOS m 
        ON i.Codigo_Barra_MedicamentoID = m.Codigo_Barra_MedicamentoID
    INNER JOIN COMPRAS c 
        ON i.CompraID = c.CompraID
    INNER JOIN INVENTARIOS_MEDICAMENTOS inv
        ON inv.MedicamentoID = m.MedicamentoID 
        AND inv.SucursalID = c.SucursalID
    WHERE i.Codigo_Barra_MedicamentoID IS NOT NULL;

    UPDATE inv
    SET inv.Stock_Actual = inv.Stock_Actual + i.Cantidad
    FROM inserted i
    INNER JOIN PRODUCTOS p 
        ON i.Codigo_Barra_ProductoID = p.Codigo_Barra_ProductoID
    INNER JOIN COMPRAS c 
        ON i.CompraID = c.CompraID
    INNER JOIN INVENTARIOS_PRODUCTOS inv
        ON inv.ProductoID = p.ProductoID 
        AND inv.SucursalID = c.SucursalID
    WHERE i.Codigo_Barra_ProductoID IS NOT NULL;

END
GO